pipeline {
    agent any


    environment {
    SVC_ACCOUNT_KEY = credentials('srinu')
  }
     
    stages {
        stage ('checkout'){
            steps {
                git branch: 'master', url: 'https://github.com/SrinuVadlapudi/gcp-devops.git'
            }
        }		
	   
      

		stage('Set Terraform path') {
            steps {
                script {
                    def tfHome = tool name: 'Terraform'
                    env.PATH = "${tfHome}:${env.PATH}"
                }
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./VM-VPC/srinu2-14f292a3a4e3.json'
		sh 'pwd'
                sh 'terraform --version'               
               
            }
        }
        
       
	    	stage('Terraform DESTROY') {
		 steps {  
			  dir('VM-VPC')
			 {
                sh 'terraform destroy -auto-approve'
			 }
		 }
	}
                             
}
}
